apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx1
    image: nginx:latest
    ports:
    - containerPort: 81
  - name: nginx2
    image: nginx:latest
    ports:
    - containerPort: 82
